openapi: 3.0.3
info:
  title: Downstream Mask Service API
  description: |
    下游遮罩服務 API，用於處理敏感資料的遮罩與加密。
    
    **部署環境**：與 BOA 批次轉檔服務在同一個 Kubernetes 叢集內
    **認證方式**：無需 Token（內部服務間通訊）
    **支援格式**：Parquet
  version: 1.0.0
  contact:
    name: API Support
    email: api-support@example.com

servers:
  - url: http://mask-service.default.svc.cluster.local:8080
    description: K8s cluster internal service (UT)
  - url: http://mask-service.uat.svc.cluster.local:8080
    description: K8s cluster internal service (UAT)
  - url: http://mask-service.prod.svc.cluster.local:8080
    description: K8s cluster internal service (PROD)

paths:
  /mask/process:
    post:
      summary: Submit file processing request
      description: 提交批次檔案處理請求，進行敏感資料的遮罩
      operationId: submitMaskingRequest
      tags:
        - Masking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaskRequest'
            examples:
              example1:
                summary: Customer data with masking
                value:
                  task_id: "transformat_202512060001"
                  input_file_path: "/data/output/customer_20251206.parquet"
                  output_file_path: "/data/masked/customer_20251206.parquet"
                  field_configs:
                    - field_name: "customer_name"
                      transform_type: "mask"
                    - field_name: "id_number"
                      transform_type: "mask"
                    - field_name: "account_balance"
                      transform_type: "encrypt"
      responses:
        '202':
          description: Request accepted, processing in progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaskResponse'
              examples:
                example1:
                  value:
                    task_id: "transformat_202512060001"
                    status: "processing"
                    message: "Request accepted"
                    submitted_at: "2025-12-06T10:00:00Z"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    error_code: "INVALID_REQUEST"
                    message: "Missing required field: task_id"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    error_code: "INTERNAL_ERROR"
                    message: "Failed to process request"

  /mask/status/{task_id}:
    get:
      summary: Query processing status
      description: 查詢批次檔案處理任務的執行狀態
      operationId: queryMaskingStatus
      tags:
        - Masking
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
            pattern: '^transformat_\d{12}$'
          example: "transformat_202512060001"
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
              examples:
                processing:
                  summary: Task is processing
                  value:
                    task_id: "transformat_202512060001"
                    status: "processing"
                    submitted_at: "2025-12-06T10:00:00Z"
                    progress: 50
                completed:
                  summary: Task completed
                  value:
                    task_id: "transformat_202512060001"
                    status: "completed"
                    submitted_at: "2025-12-06T10:00:00Z"
                    completed_at: "2025-12-06T10:05:30Z"
                    progress: 100
                failed:
                  summary: Task failed
                  value:
                    task_id: "transformat_202512060001"
                    status: "failed"
                    submitted_at: "2025-12-06T10:00:00Z"
                    failed_at: "2025-12-06T10:02:15Z"
                    error_message: "Invalid parquet file format"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    error_code: "TASK_NOT_FOUND"
                    message: "Task ID not found: transformat_202512060999"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    MaskRequest:
      type: object
      required:
        - task_id
        - input_file_path
        - output_file_path
        - field_configs
      properties:
        task_id:
          type: string
          description: 任務唯一識別碼
          pattern: '^transformat_\d{12}$'
          example: "transformat_202512060001"
        input_file_path:
          type: string
          description: 輸入 Parquet 檔案的完整路徑
          example: "/data/output/customer_20251206.parquet"
        output_file_path:
          type: string
          description: 輸出 Parquet 檔案的完整路徑
          example: "/data/masked/customer_20251206.parquet"
        field_configs:
          type: array
          description: 欄位轉碼設定
          items:
            $ref: '#/components/schemas/FieldConfig'
          minItems: 1

    FieldConfig:
      type: object
      required:
        - field_name
        - transform_type
      properties:
        field_name:
          type: string
          description: 欄位名稱
          example: "customer_name"
        transform_type:
          type: string
          description: 轉碼型態
          enum:
            - plain
            - mask
            - encrypt
          example: "mask"

    MaskResponse:
      type: object
      required:
        - task_id
        - status
        - submitted_at
      properties:
        task_id:
          type: string
          description: 任務 ID
          example: "transformat_202512060001"
        status:
          type: string
          description: 任務狀態
          enum:
            - processing
            - completed
            - failed
          example: "processing"
        message:
          type: string
          description: 回應訊息
          example: "Request accepted"
        submitted_at:
          type: string
          format: date-time
          description: 提交時間 (ISO 8601)
          example: "2025-12-06T10:00:00Z"

    StatusResponse:
      type: object
      required:
        - task_id
        - status
        - submitted_at
      properties:
        task_id:
          type: string
          description: 任務 ID
          example: "transformat_202512060001"
        status:
          type: string
          description: 任務狀態
          enum:
            - processing
            - completed
            - failed
          example: "completed"
        submitted_at:
          type: string
          format: date-time
          description: 提交時間
          example: "2025-12-06T10:00:00Z"
        completed_at:
          type: string
          format: date-time
          description: 完成時間（狀態為 completed 時）
          example: "2025-12-06T10:05:30Z"
        failed_at:
          type: string
          format: date-time
          description: 失敗時間（狀態為 failed 時）
          example: "2025-12-06T10:02:15Z"
        error_message:
          type: string
          description: 錯誤訊息（狀態為 failed 時）
          example: "Invalid parquet file format"
        progress:
          type: integer
          description: 處理進度（0-100）
          minimum: 0
          maximum: 100
          example: 50

    ErrorResponse:
      type: object
      required:
        - error_code
        - message
      properties:
        error_code:
          type: string
          description: 錯誤代碼
          example: "INVALID_REQUEST"
        message:
          type: string
          description: 錯誤訊息
          example: "Missing required field: task_id"
        details:
          type: object
          description: 詳細錯誤資訊
          additionalProperties: true

tags:
  - name: Masking
    description: 資料遮罩與加密相關操作
